language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly

# faster builds on new travis setup not using sudo
sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"

script:
  # validate composer.json
  - composer validate --no-check-lock
  - composer install

